workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Moblin.xcworkspace"
        XCODE_SCHEME: "Moblin"
    scripts:
      - name: Install dependencies
        script: |
          gem install bundler
          bundle install
          pod install
      - name: Build app
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $HOME/build/Moblin.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive -archivePath $HOME/build/Moblin.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $HOME/build
    artifacts:
      - build/*.ipa
